---
kind: pipeline
type: kubernetes
name: build

steps:
  - name: build & push
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-base-image
      tags:
        - ${DRONE_COMMIT_SHA}
        - branch-${DRONE_COMMIT_BRANCH/\//_}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        exclude:
          - main
    depends_on:
      - clone

  - name: build & push latest
    image: plugins/docker
    settings:
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-base-image
      tags:
        - ${DRONE_COMMIT_SHA}
        - build_${DRONE_BUILD_NUMBER}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    when:
      branch:
        include:
          - main
    depends_on:
      - clone

trigger:
  event:
    - push
