---
kind: pipeline
type: kubernetes
name: build libreoffice-base-build
trigger:
  event:
    - push
  branch:
    exclude:
      - main

steps:
  - name: build & push libreoffice jdk
    image: plugins/docker
    settings:
      dockerfile: libreoffice-base-build/Dockerfile
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-libreoffice-build
      tags:
        - ${DRONE_COMMIT_SHA}
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - clone

---
kind: pipeline
type: kubernetes
name: build libreoffice-base-build tag
trigger:
  event:
    - tag
  branch:
    - main

steps:
  - name: build & push libreoffice jdk latest
    image: plugins/docker
    settings:
      dockerfile: Dockerfile-jdk
      registry: quay.io
      repo: quay.io/ukhomeofficedigital/hocs-libreoffice-build
      tags:
        - ${DRONE_TAG}
        - ${DRONE_COMMIT_SHA}
        - latest
    environment:
      DOCKER_PASSWORD:
        from_secret: QUAY_ROBOT_TOKEN
      DOCKER_USERNAME: ukhomeofficedigital+hocs_quay_robot
    depends_on:
      - clone
