name: 'SemVer - Tag on Merge'
on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    name: SemVer - Tag on Merge
    runs-on: ubuntu-latest
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'skip-release') == false
    steps:
      - id: label
        uses: UKHomeOffice/match-label-action@v1
        with:
          labels: minor,major,patch
          mode: singular
      - uses: UKHomeOffice/semver-tag-action@v2
        with:
          increment: ${{ steps.label.outputs.matchedLabels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_use_head_tag: ${{ github.base_ref == 'main' }}
