name: SemVer
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: bump
        uses: UKHomeOffice/match-label-action@v3
        with:
          allowed: major, minor, patch
      - uses: UKHomeOffice/semver-release-action@v3
        with:
          bump: ${{ steps.bump.outputs.match }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
